// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VPDecijeIgracke.Context;

#nullable disable

namespace VPDecijeIgracke.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240411171602_InitialCreateDatabase")]
    partial class InitialCreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VPDecijeIgracke.Models.AdministratorModel.Administrator", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"), 1L, 1);

                    b.Property<string>("AdresaAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImeAdmin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KorisnickoImeAdmin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LozinkaAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrezimeAdmin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.HasIndex("EmailAdmin")
                        .IsUnique();

                    b.HasIndex("KorisnickoImeAdmin")
                        .IsUnique();

                    b.HasIndex("LozinkaAdmin")
                        .IsUnique();

                    b.ToTable("Administrator");
                });

            modelBuilder.Entity("VPDecijeIgracke.Models.KategorijaProizvodaModel.Kategorija", b =>
                {
                    b.Property<int>("KategorijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategorijaID"), 1L, 1);

                    b.Property<string>("NazivKategorije")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("KategorijaID");

                    b.HasIndex("NazivKategorije")
                        .IsUnique();

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("VPDecijeIgracke.Models.KorisnikModel.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikID"), 1L, 1);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.HasIndex("Lozinka")
                        .IsUnique();

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("VPDecijeIgracke.Models.PorudzbinaModel.Porudzbina", b =>
                {
                    b.Property<int>("PorudzbinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PorudzbinaID"), 1L, 1);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PorudzbinaID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Porudzbina");
                });

            modelBuilder.Entity("VPDecijeIgracke.Models.ProizvodModel.Proizvod", b =>
                {
                    b.Property<int>("ProizvodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodID"), 1L, 1);

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KategorijaID")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("NazivProizvoda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SlikaURL")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("ProizvodID");

                    b.HasIndex("AdminID");

                    b.HasIndex("KategorijaID");

                    b.HasIndex("NazivProizvoda")
                        .IsUnique();

                    b.HasIndex("SlikaURL")
                        .IsUnique();

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("VPDecijeIgracke.Models.StavkaPorudzbineModel.StavkaPorudzbine", b =>
                {
                    b.Property<int>("StavkaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StavkaID"), 1L, 1);

                    b.Property<decimal>("CenaStavka")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KolicinaStavka")
                        .HasColumnType("int");

                    b.Property<int>("PorudzbinaID")
                        .HasColumnType("int");

                    b.Property<int>("ProizvodID")
                        .HasColumnType("int");

                    b.HasKey("StavkaID");

                    b.HasIndex("PorudzbinaID");

                    b.HasIndex("ProizvodID");

                    b.ToTable("StavkaPorudzbine");
                });

            modelBuilder.Entity("VPDecijeIgracke.Models.PorudzbinaModel.Porudzbina", b =>
                {
                    b.HasOne("VPDecijeIgracke.Models.KorisnikModel.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("VPDecijeIgracke.Models.ProizvodModel.Proizvod", b =>
                {
                    b.HasOne("VPDecijeIgracke.Models.AdministratorModel.Administrator", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VPDecijeIgracke.Models.KategorijaProizvodaModel.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrator");

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("VPDecijeIgracke.Models.StavkaPorudzbineModel.StavkaPorudzbine", b =>
                {
                    b.HasOne("VPDecijeIgracke.Models.PorudzbinaModel.Porudzbina", "Porudzbina")
                        .WithMany()
                        .HasForeignKey("PorudzbinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VPDecijeIgracke.Models.ProizvodModel.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Porudzbina");

                    b.Navigation("Proizvod");
                });
#pragma warning restore 612, 618
        }
    }
}
